<div class="container">
  <div class="row">
    <div class="col-lg">
      <h1 class='text-uppercase font-weight-bold mt-3 mb-5  text-center' >Часто задаваемые вопросы FAQ</h1>
      <?php
        foreach($faqGroups as $faqGroup) {
          echo "<h2 style='color:#cc0001' class='mt-3 mb-3 text-uppercase text-center font-weight-bold'>".$faqGroup->faq_group_title."</h2>";
          $group_id = $faqGroup->faq_group_id;
          $faqs = Faqs::find([
            'conditions' => "faq_group_id=$group_id AND faq_hidden='0'",
            'order' => 'faq_position ASC'
          ]);
          foreach($faqs as $faq) {
            echo "<h3 class='mt-3 mb-3 text-uppercase font-weight-bold'>".$faq->faq_title."</h3>";
            echo "<p class='text-justify'>".$faq->faq_description."</p>";
            echo "<a href='#' style='color:#cc0001'>Наверх</a>";
          }
        }
       ?>
    </div>
  </div>
</div>
