<div class="container text-center">
  <div class="row">
    <div class="col-lg">
      <h1 class='mt-3'>Автомобили Tesla</h1>
      <h4 class='font-italic'>Наша цель — cделать электромобили доступными</h4>
      <p class='text-center'>Мы популяризируем автомобили на электротяге и развенчиваем мифы о них на собственном примере. Наш клуб объединил людей с неординарными ценностями и взглядами на жизнь. Своим примером и действиями мы не только демонстрируем преимущества электромобилей. Мы также приближаем будущее, в котором экологически чистому транспорту будет отведена одна из ведущих ролей. </p>
      <img src="img/tesla-roadster-2.0-team.jpg" class='img img-fluid' alt="team">
    </div>
  </div>
  <div class="row">
    <h1 class='mt-3'>Мы продаем и устанавливаем зарядные станции для электромобилей</h1>
    <div class="col-lg-4">
      <p class='mt-3 font-weight-bold'>Для быстрой зарядки</p>
      <small><p>Адаптированы под российские условия</p></small>
      <img src="img/charging-01.jpg" alt="charging">
    </div>
    <div class="col-lg-4">
      <p class='mt-3 font-weight-bold'>Для публичного использования</p>
      <small><p>Все станции имеют гарантию</p></small>
      <img src="img/charging-02.jpg" alt="charging">
    </div>
    <div class="col-lg-4">
      <p class='mt-3 font-weight-bold'>Для дома и офиса</p>
      <small><p>Установим в удобном вам месте</p></small>
      <img src="img/charging-03.jpg" alt="charging">
    </div>
  </div>
  <div class="row">
    <div class="col-lg">
      <h1 class='mt-3'>Карта зарядных станций</h1>
      <iframe id='chargingMap' src='https://www.plugshare.com/widget2.html?latitude=55.755826&longitude=37.6172999&spanLat=1.44567&spanLng=1.44567&plugs=1,2,3,4,5,6,42,13,7,8,9,10,11,12,14,15,16,17' class='w-100' allow='geolocation'></iframe>
    </div>
  </div>
  <h1 class='mt-3'>Плюсы электромобилей</h1>
  <div class="row text-center">
    <div class="col-lg-3">
      <img class='indexCard img img-fluid mb-3' src="img/tehnologii-9ea0012e.png" alt="image">
      <h5 class='text-uppercase'>Технологии</h5>
      <p>Запас хода электромобиля составляет от 100 до 800 км, в зависимости от емкости аккумулятора</p>
    </div>
    <div class="col-lg-3">
      <img class='indexCard img img-fluid mb-3' src="img/dvigatel-00da750a.png" alt="image">
      <h5 class='text-uppercase'>Двигатель</h5>
      <p>Электрический двигатель прослужит намного дольше, а по мощности не уступит бензиновому</p>
    </div>
    <div class="col-lg-3">
      <img class='indexCard img img-fluid mb-3' src="img/tihii-hod-d37d491e.png" alt="image">
      <h5 class='text-uppercase'>Тихий ход</h5>
      <p>В электрическом транспорте нет привычного, шумного двигателя и выхлопа которые создают шум</p>
    </div>
    <div class="col-lg-3">
      <img class='indexCard img img-fluid mb-3' src="img/tihii-hod-d37d491e.png" alt="image">
      <h5 class='text-uppercase'>Вместительность</h5>
      <p>За счет компактного двигателя и отсутствии узлов, во многих электромобилях имеется дополнительный багажник</p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3">
      <img class='indexCard img img-fluid mb-3' src="img/bezopasnost-0bf90b03.png" alt="image">
      <h5 class='text-uppercase'>Безопасность</h5>
      <p>Экотранспорт оснащен самыми современными и надежными системами безопасности</p>
    </div>
    <div class="col-lg-3">
      <img class='indexCard img img-fluid mb-3' src="img/ecologia-21d4b028.png" alt="image">
      <h5 class='text-uppercase'>Экология</h5>
      <p>0 % вредных выбросов в окружающую среду и атмосферу. 100 % экологически чистый транспорт</p>
    </div>
    <div class="col-lg-3">
      <img class='indexCard img img-fluid mb-3' src="img/economia-e51dfbc6.png" alt="image">
      <h5 class='text-uppercase'>Экономия</h5>
      <p>Эксплуатация электромобиля обойдется дешевле в 6-8 раз, по сравнению с обычным автомобилем</p>
    </div>
    <div class="col-lg-3">
      <img class='indexCard img img-fluid mb-3' src="img/Budushhee-3d978d04.png" alt="image">
      <h5 class='text-uppercase'>Будущее</h5>
      <p>Тенденция электрификации растет с каждым годом на мировом уровне. Электромобили – наше будущее</p>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-lg">
      <h1 class='font-weight-bold font-italic'>Давайте улучшать этот мир вместе!</h1>
      <div id='carouselExampleIndicators' class="carousel slide" data-ride="carousel" data-interval='3000'>
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="img/db536c08-tesla-s3xy-2.jpg" alt="first slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="img/45e88f63-sx3semi-family.jpg" alt="second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="img/tesla-family-model-3-s-x.webp" alt="third slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="img/tesla-lineup-sexyr.jpg" alt="fourth slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="img/tesla-supercharging-group.webp" alt="fifth slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
    <div class="row mt-3">
      <div class="col-lg">
        <a class=' text-uppercase mt-5' id='toCatalog' href="/index/catalog">В каталог</a>
      </div>
    </div>
</div>
