<header class="container-fluid text-center">
    <nav class="navbar navbar-expand-lg">
      <a class="navbar-brand" href="/">
        <?php
          use Phalcon\Tag;
          echo Tag::image(
            [
              'img/logo.jpg',
              'alt' => 'Logo',
              'width' => '80',
            ]
          );
         ?>
         <span class='text-uppercase'>Belgorod Tesla Club</span>
      </a>
      <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav m-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Главная</a>
          </li>
          <li class="nav-item">
           <a class="nav-link" href="/index/team">Наша команда</a>
          </li>
          <li class="nav-item">
           <a class="nav-link" href="/index/catalog">Каталог товаров</a>
          </li>
          <li class="nav-item">
           <a class="nav-link" href="/index/faq">FAQ</a>
          </li>
          <li class="nav-item">
           <a class="nav-link" href="/index/contact">Контакты</a>
          </li>
          <li class="nav-item">
           <a class="nav-link" href="/index/cart">Корзина</a>
          </li>
        </ul>
      </div>
    </nav>
</header>
